
export const Badges = [
  {
    url:
      "https://api.badgr.io/public/assertions/tToNVYemQ2u2Ezx_G62gfw?embedVersion=1"
  },
  {
    url:
      "https://api.badgr.io/public/assertions/25q8i88NSAOxPiiIbc7Xrg?embedVersion=1"
  },
  {
    url:
      "https://api.badgr.io/public/assertions/6TKNTGRHTZO-WFQfBmGb9g?embedVersion=1"
  },
  {
    url:
      "https://api.badgr.io/public/assertions/5YgEALZ1TJyPdNgtLwiSfQ?embedVersion=1"
  },
  {
    url:
      "https://api.badgr.io/public/assertions/raLAh1uSTnq5GC1Kd68tdw?embedVersion=1"
  },
  {
    url:
      "https://api.badgr.io/public/assertions/RKw_3HXIRmeD1ZFI6ZUkRQ?embedVersion=1"
  },
  {
    url:
      "https://api.badgr.io/public/assertions/MnccSnd1TrqR67JrZqM0cQ?embedVersion=1"
  },
  {
    url:
      "https://api.badgr.io/public/assertions/LoieeF5lTYiBaLw6U7FNAA?embedVersion=1"
  },
  {
    url:
      "https://api.badgr.io/public/assertions/lBHzRl78QR6KO9qkYkVxww?embedVersion=1"
  },
  {
    url:
      "https://api.badgr.io/public/assertions/rF9zuOWfTu-wKl4XhacsUA?embedVersion=1"
  },
  {
    url:
      "https://api.badgr.io/public/assertions/OqDaRwkFScqgoekHVTI2Kg?embedVersion=1"
  },
  {
    url:
      "https://api.badgr.io/public/assertions/03DXUGGSS1aWbSCT5PmnmQ?embedVersion=1"
  }
];
